all:  signal1 signal2 signal3 signal4 signal5

signal1: signal1.c
	gcc -o signal1 -g -Wall signal1.c

signal2: signal2.c
	gcc -o signal2 -g -Wall signal2.c


signal3: signal3.c
	gcc -o signal3 -g -Wall signal3.c

signal4: signal4.c
	gcc -o signal4 -g -Wall signal4.c

signal5: signal5.c
	gcc -o signal5 -g -Wall signal5.c

clean:
	rm signal1 signal2 signal3 signal4 signal5
